### PR TITLE
Background color changed

### LINKED ISSUE #9: Upadate background color to brown
image

### PR DESCRIPTION
**Pull request by GeviReddy**

### CODE REVIEW

**Comment by indu173** [comment]
you chnaged button color, but the chnage is for Background color

image

**Comment by GeviReddy** [comment]
Yeah sure i will fix it.

**Comment by GeviReddy** [comment]
fixed

**Comment by GeviReddy** [comment]
fixed

**Comment by indu173** [comment]
Its working, Thanks @GeviReddy

**Pull request closed without merging**
